### ISSUE TITLE
classic update?

### ISSUE THREAD

**Issue by amey1956** [Ravendwyr/Chinchilla#39]
just checking to see if its even on the radar.

**Comment by EthanCentaurai** [comment]
I want to but I can't guarantee anything at the moment. It definitely won't be ready for launch day though.

**Comment by Solithe** [comment]
No matter when, but thanks for the answer. This is the best Minimap addon in wow in my opinion.

=)

**Comment by Solithe** [comment]
is there any news about the classic version? =)

sry but i can´t wait for it =D

**Comment by Ravendwyr** [comment]
Please download [v2.10.0-beta1](https://www.curseforge.com/wow/addons/chinchilla/files/all) when it becomes available and let me know how things go.

**Comment by Ravendwyr** [comment]
Closing this now as I haven't been told of any issues in the last three weeks. 👍
