### ISSUE TITLE
Classic Tracking Dots

### ISSUE THREAD

**Issue by l3uGsY** [Ravendwyr/Chinchilla#40]
Tracking Dots on the Beta Classic Chinchilla do not differentiate between NPC and Player or Enemy Player.

Unsure if this is even possible, I can't recall if the game even had separate tints between them.

**Comment by Ravendwyr** [comment]
That's how things were in Classic I'm afraid. Very little was displayed on the minimap back then and many things used the same blip (quest turn-ins are the same as tracked herbs/mines for instance).

This is the expected behaviour for Classic and I strongly believe it cannot be worked around.
