### ISSUE TITLE
Tracking Dots

### ISSUE THREAD

**Issue by l3uGsY** [Ravendwyr/Chinchilla#42]
Sorry I always come with bad news.  Blizzard did a thing a again.  Tracking Dots are all messed with the latest patch.  

:(

**Comment by Ravendwyr** [comment]
I had a feeling this was going to happen. 😛

I'll work on it tomorrow after the patch goes live on EU servers.

**Comment by zalidthebur** [comment]
Why do they keep doing this. Hopefully it's an easy thing to fix yet again. Thanks Ravendwyr :-)

**Comment by Amierlyn** [comment]
Any word when this is going to get fixed?

**Comment by Ravendwyr** [comment]
It will be sorted by the end of today. Something came up and I needed to focus on that first. 🙁

**Comment by Ravendwyr** [comment]
I'm assuming the blips are okay on Classic servers? I let my sub lapse and can't check.

**Comment by TorenAltair** [comment]
It seems the dots for Nandini and Nandini new got mixed up: the NSCs are now crosses, I think the other players were crosses before and not dots as now

**Comment by Ravendwyr** [comment]
Whoops.

**Comment by Amierlyn** [comment]
i look forward to seeing this fixed soon i really enjoy the addon.

**Comment by Ravendwyr** [comment]
I haven't heard anything otherwise so I'm going to close this as fixed and push a release package to CurseForge. 👍
