### ISSUE TITLE
Guess who patched...  :(

### ISSUE THREAD

**Issue by l3uGsY** [Ravendwyr/Chinchilla#48]
And I would imagine the Color Blind Tracking Dots are messed.  What I was able to look up about the below issues.

> I've found that any code that has something like SetBackdrop causes lua errors in game. and commenting those out for me in sptimers and omen stopped them reporting errors but i dont think the addon gets broken by doing that.  So i dont know if any LUI code uses that setbackdrop code or not.

As always, thank you for keeping this addon alive.  The tracking dots alone, I couldn't live without and coupled with the rest of the options, it's the perfect package.

`Message: Interface\AddOns\Chinchilla\Modules\Coordinates.lua:59: attempt to call method 'SetBackdrop' (a nil value)
Time: Wed Oct 14 02:17:07 2020
Count: 1
Stack: Interface\AddOns\Chinchilla\Modules\Coordinates.lua:59: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\Chinchilla\Modules\Coordinates.lua"]:59: in function <Interface\AddOns\Chinchilla\Modules\Coordinates.lua:49>
[string "=[C]"]: ?
[string "@Interface\AddOns\Chinchilla\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...AddOns\Chinchilla\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Chinchilla\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Chinchilla\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@Interface\AddOns\Chinchilla\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:620: in function <...AddOns\Chinchilla\Libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:495: in function `UIParentLoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:542: in function `CombatLog_LoadUI'
[string "@Interface\FrameXML\UIParent.lua"]:1375: in function <Interface\FrameXML\UIParent.lua:1258>

Locals: <none>`

`Message: Interface\AddOns\Chinchilla\Modules\Location.lua:43: attempt to call method 'SetBackdrop' (a nil value)
Time: Wed Oct 14 02:17:07 2020
Count: 1
Stack: Interface\AddOns\Chinchilla\Modules\Location.lua:43: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\Chinchilla\Modules\Location.lua"]:43: in function <Interface\AddOns\Chinchilla\Modules\Location.lua:33>
[string "=[C]"]: ?
[string "@Interface\AddOns\Chinchilla\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...AddOns\Chinchilla\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Chinchilla\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Chinchilla\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@Interface\AddOns\Chinchilla\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:620: in function <...AddOns\Chinchilla\Libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:495: in function `UIParentLoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:542: in function `CombatLog_LoadUI'
[string "@Interface\FrameXML\UIParent.lua"]:1375: in function <Interface\FrameXML\UIParent.lua:1258>

Locals: <none>`

**Comment by jnsebgosselin** [comment]
I think this is related to ttps://www.wowhead.com/news=316954/addons-now-available-for-use-in-shadowlands-beta

> One of the major changes in 9.0 is a change to SetBackdrop. The TL/DR, on live, 100% of frames support backdrops, whether they are used or not. 1000s of frames between every addon and default UI, even frames that never see such as event frames have backdrops. UI team realized this is a serious performance issue. so effective in 9.0, no frames have backdrops unless the addon imports/inherits the backdrop template.
this means addons that aren't importing them now throw nil errors with method "Setbackdrop". This issue affects a large number of addons.
