### ISSUE TITLE
no location above the minimap

### ISSUE THREAD

**Issue by Solithe** [Ravendwyr/Chinchilla#52]
Hey. Since the Prepatch there is no Location above the Minimap and a LUA Error

3x Chinchilla\Modules\Location.lua:106: attempt to index field 'closeButton' (a nil value)
[string "@Chinchilla\Modules\Location.lua"]:106: in function <Chinchilla\Modules\Location.lua:33>
[string "=[C]"]: ?
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:520>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Ace3\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:51: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49>
[string "@Ace3\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:843: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:664>
[string "=[C]"]: ?
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Ace3\AceGUI-3.0-41\widgets\AceGUIWidget-CheckBox.lua"]:68: in function <...ns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:57>

Greetings
Soli from Discord

**Comment by adrnde** [comment]
Less annoying, but possibly a warning of future breakage, is that nothing is 'sticky' anymore. You can set the location of the Garrison button, but as soon as you reload, it will be back to its position at the bottom left of the minimap.

**Comment by Ravendwyr** [comment]
Think this is a duplicate of #48 and #53.
