### ISSUE TITLE
Expander opacity and elements' visibility issues

### ISSUE THREAD

**Issue by the-chuppa** [Ravendwyr/Chinchilla#60]
Hey, great addon, used it for many years, mainly because of the Expander feature. Now to the matter at hand, I encountered several issues with the Expander.

**Describe the bug**
1. Expander ignores set opacity and is always at Appearance opacity instead.
2. Location is not being hidden by using Expander. If that is the expected behaviour, the position of the Location is not being scaled with the Expander. 
3. MinimapButtonBag addon's button is not being hidden when using the Expander.

**To Reproduce**
1. Set the Expander opacity to a value different from Appearance opacity
2. Toggle on the Expander
3. See that the Expander is not at set opacity. Also Location is visible and close to the middle of the Expander if size is >100%. Also MBB addon's button is visible.

**Expected behavior**
I would expect the opacity to be at set value and Location and other addons' buttons hidden.

**WoW version**
Retail, latest addon version.

**Comment by stoglim** [comment]
This is addressed in https://github.com/Ravendwyr/Chinchilla/pull/54

**Comment by the-chuppa** [comment]
Great, that's 1st issue solved. Any info on the other two issues?
