### ISSUE TITLE
MINIMAP_UPDATE_ZOOM event spam

### ISSUE THREAD

**Issue by Ravendwyr** [Ravendwyr/Chinchilla#61]
Note to self:

The `MINIMAP_UPDATE_ZOOM` event is firing on every single frame due to how we abuse the `Minimap:GetZoom()` and `Minimap:SetZoom()` functions to detect if we're indoors or not. While seemingly harmless to the end user, this is A Bad Thing™️ and should probably not be happening.

**Comment by Daeveren** [comment]
This does really bad things to the fps on its own (-10 fps for me, tested when looking at a wall in Torghast, 230 fps with Chinchilla disabled, 200 fps with Chinchilla enabled). I had a Weak Aura installed which also was registering MINIMAP_UPDATE_ZOOM and together, both, were lowering the fps from 100 to 50 fps outdoors in the Bastion zone, while standing still. Now the Weak Aura author - https://wago.io/CurrencyAndItemTracker - has just added a 0.2 sec throttle to his MINIMAP_UPDATE_ZOOM calls and the 'halving' of my fps is no more, but it's now down to reducing my fps by exactly 10% as I've said above. Please, atleast add a throttle if a better solution cannot be (easily) found - I suppose even 0.5 sec is more than acceptable. Losing fps over such a minor thing is sad.
