### ISSUE TITLE
Broken tracking dots 

### ISSUE THREAD

**Issue by Athanair** [Ravendwyr/Chinchilla#63]
**Describe the bug**
Only blizzard tracking dots work, all others have messed up icons

**WoW version**
Retail 9.0.2.36665

**Comment by Ravendwyr** [comment]
I have a sneaky suspicion your installed version of Chinchilla is out of date, unless a client patch went live without me noticing.

Please make sure you have [the latest version](https://www.curseforge.com/wow/addons/chinchilla/files/all) installed.

**Comment by Athanair** [comment]
It was working yesterday, today after the update became like that, i just tested with your link same thing
![1](https://user-images.githubusercontent.com/74628845/99461010-b7cf5a80-290f-11eb-9f44-51568deda3f9.png)
![2](https://user-images.githubusercontent.com/74628845/99461022-bef66880-290f-11eb-9432-81dd110158cd.png)

**Comment by Ravendwyr** [comment]
Welp, that would do it then. The patch hasn't gone live on EU realms yet hence my comments earlier. I'll look into this after the the update.

**Comment by Athanair** [comment]
Oh! Thanks for your attention, this addon saves, hunter tracking with resources is very messy.

**Comment by stoglim** [comment]
I've updated sprite sheets and opened a PR: https://github.com/Ravendwyr/Chinchilla/pull/64.
I have a feeling that some artist just likes to move sprites around.
