### ISSUE TITLE
Garrison Report button completely disappeared

### ISSUE THREAD

**Issue by BigFire321** [Ravendwyr/Chinchilla#67]
Version v2.10.2-11-gd3419a1 Garrison Report button completely disappeared.  Previously, I can temporillary have it anchored to the minimap by disabling and enabling it.  Currently it is just not there.

**To Reproduce**
1. Go to Show / Hide
2. Click on Garrison checkbox (to remove it)
3. Click on Close
4. Go to Show / Hide
5. Click on Garrison check box (to enable it)
6. Click on Close

**Expected behavior**
Previously that's the method of anchoring the garrison button if you've moved the minimap from default location.  Currently it's just not there.

**WoW version**
Retail 9.0.2

**Comment by stoglim** [comment]
Was the garrison button showing prior to disabling it?
Does the garrison button show if you disable Chinchilla?

**Comment by BigFire321** [comment]
NVM, they seem to have removed that button completely.....
