### ISSUE TITLE
Tracking dots not working.

### ISSUE THREAD

**Issue by griddark** [Ravendwyr/Chinchilla#71]
**Describe the bug**
Tracking dots not working properly.

**To Reproduce**
Select different tracking dots.

**Expected behavior**
Tracking dots change to expected appearence.

**Screenshots**
https://puu.sh/GRSax/ee9f2a8620.jpg

**WoW version**
Retail

**Additional context**
Just adding bug, headlinerko posted in comments, I also experienced it.

**Comment by Ravendwyr** [comment]
Duplicate of #48 and #63
