### ISSUE TITLE
Vehicle Seat Indicator

### ISSUE THREAD

**Issue by Hmmharold** [Ravendwyr/Chinchilla#76]
Can you please add a mover for the Vehicle Seat Indicator?

**Comment by Hmmharold** [comment]
My apologies! I noticed this feature was already added to the LUA on GitHub but not uploaded to the Curseforge bundle

**Comment by Ravendwyr** [comment]
I really should update the CurseForge package. :/
Closing this as a dupe of #44, #66, and #75 for now.
