### ISSUE TITLE
[BUG] Yet another tracking dots change by Blizz

### ISSUE THREAD

**Issue by l3uGsY** [Ravendwyr/Chinchilla#77]
Like always, the tracking dots have been shuffled around again.

And like always, thank you for keeping this addon going over the years.  I truly appreciate it.

**Comment by Ravendwyr** [comment]
Can't say I'm surprised. 😛 
I'll work on it after the patch goes live on EU realms.

**Comment by zalidthebur** [comment]
I just noticed this and glad you are on top of it again. Look forward to the fix :-)

**Comment by Ravendwyr** [comment]
Try the latest alpha on CurseForge and let me know how it goes.

**Comment by Discomanco** [comment]
Feels good to have the right tracking dots back again, its been a weird week :D  
Nandini New working just fine

**Comment by Ravendwyr** [comment]
Awesome. I'll keep an eye on things and if nothing else bad happens in the next day or so I'll close the issue and make a new Release package on CurseForge and WoWInterface.

**Comment by zalidthebur** [comment]
Thanks for the fix in alpha :-)
