### ISSUE TITLE
[BUG] v2.12.1 introduced bug leading to chinchilla and its configuration page no longer loading

### ISSUE THREAD

**Issue by tymoorej** [Ravendwyr/Chinchilla#81]
**Describe the bug**
After updating to v2.12.1 chinchilla no longer works for me and /chin no longer opens any configuration panel

**To Reproduce**
Upgrade to v2.12.1 of chinchilla

**Expected behaviour**
Chincilla should be active and I should be able to open up the configuration panel

**WoW version**
v2.12.1 for TBC.

**Comment by Ravendwyr** [comment]
Unable to reproduce. Do you notice any error messages?

If you installed the addon manually, please be sure that the file path is `_classic_/Interface/AddOns/Chinchilla/Chinchilla.toc`

**Comment by tymoorej** [comment]
Closing this issue, restarting the game entirely seemed to fix the issue.
