### ISSUE TITLE
New patch, sprites moved around again

### ISSUE THREAD

**Issue by Discomanco** [Ravendwyr/Chinchilla#82]
Because of course they did, but you probably already knew that, but I'm making an issue anyway :)

![image](https://user-images.githubusercontent.com/4707702/123927488-2f2c9880-d98d-11eb-89b2-92496de39bd0.png)

**Comment by Discomanco** [comment]
New blips work beautifully 👍

**Comment by Ravendwyr** [comment]
Awesome. 👍🏻 
I'll keep an eye on things and will make a new Release package on CurseForge if nothing else crops up.
