### ISSUE TITLE
[BUG] Tracking Dots corruption?

### ISSUE THREAD

**Issue by imershon** [Ravendwyr/Chinchilla#84]
(Apologies if I do this wrong never done one before)
Since a recent patch the tracking dots are coming up wonky.

Selecting any Tracking Dots Style other than Blizzard is showing up wonky.

**Screenshots**
![Snap 2022-04-04 at 12 47 06](https://user-images.githubusercontent.com/43586326/161465996-ec847727-fc0f-4db1-90f1-9469ec08ca2f.png)

Using Retail version

I noticed in l3uGsY's fork they updated the Nandini-New.tga and that's fixed it for that one Style
https://github.com/l3uGsY/Chinchilla/blob/master/Art/Blip-Nandini-New.tga

Thanks heaps for your time on this addon its awesome :)

**Comment by Ravendwyr** [comment]
Aye this happens with every patch. I meant to sort this over the weekend but got distracted. >_>
