### ISSUE TITLE
[BUG] LFG eye position

### ISSUE THREAD

**Issue by Mard35** [Ravendwyr/Chinchilla#90]
LFG eye icon position didn't move with minimap, no position options for it. (85e8ee3 alpha)
![Screenshot_2](https://user-images.githubusercontent.com/61734903/187970028-9893dac0-4472-4739-bf41-bae6ef2c08b3.jpg)

**Comment by Ravendwyr** [comment]
The options to move the LFG button are in the Move Buttons section of the config window.
