### ISSUE TITLE
[BUG] Quest tracker

### ISSUE THREAD

**Issue by Muballi** [Ravendwyr/Chinchilla#92]
Quest tracker is tracking only 2 quests (WOTLK). When I disable Chinchilla, the default quest tracker works normally.
I don't use any other addon that interferes the tracker.

Thanks

**Comment by Ravendwyr** [comment]
This is on Wrath Classic, right?

**Comment by Muballi** [comment]
> This is on Wrath Classic, right?

Yeah, wrath classic
