### ISSUE TITLE
[BUG] Dungeon difficulty icon position

### ISSUE THREAD

**Issue by Mard35** [Ravendwyr/Chinchilla#94]
Dungeon difficulty icon position didn't move with minimap, no position options for it.
![Screenshot_1](https://user-images.githubusercontent.com/61734903/189673644-8122842e-3ba5-4260-8998-58f5dfbdf39b.jpg)

**Comment by Ravendwyr** [comment]
Which version of Chinchilla are you using? Options to move this icon are in the Move Buttons section of the config as of v2.13.0-beta3.

**Comment by Mard35** [comment]
> Which version of Chinchilla are you using? Options to move this icon are in the Move Buttons section of the config as of v2.13.0-beta3.
Ok, i used 2.13.0-beta2
